server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

swagger:
  resourcePackage: com.ihorpolataiko.dropwizarddemo.resource
  scan: true

mongoProperties:
  dbName: "items"
  host: "localhost"
  port: 27017
